name: mami-san
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - jupyter
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - pytorch
  - torchvision=0.9.0
  - torchaudio
  - cudatoolkit=11.3
  - opencv
  - transformers
